services:
  pado-network:
    image: padolabs/pado-network:latest
    container_name: pado-network
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/pado-network/logs/
      - ${ECDSA_KEY_FILE}:/pado-network/keys/ecdsa_key.json:readonly
      - ${BLS_KEY_FILE}:/pado-network/keys/bls_key.json:readonly
      - ${LHE_KEY_PATH}:/pado-network/keys/lhe_key.json:readonly
      - ${AR_WALLET_PATH}:/pado-network/keys/ar_wallet.json:readonly
    command:
      - node
      - './dist/main.js'
