services:
  pado-network:
    image: padolabs/pado-network:latest
    container_name: pado-network-only-ao
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/pado-network/logs/
      - ${LHE_KEY_PATH}:/pado-network/keys/lhe_key.json:readonly
      - ${AR_WALLET_PATH}:/pado-network/keys/ar_wallet.json:readonly
    command:
      - node
      - './dist/main.js'
